name: Trigger Webhook

on:
  push:
    branches:
      - main
    pull_request:

jobs:

  Webhook:
    runs-on: ubuntu-latest
    - name: Call Webhook
      - uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
