name: Build and deploy

on:
  push:
    branches:
      - master
    pull_request:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Call webhook
      uses: distributhor/workflow-webhook@v1
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
